---

collections:
  - name: ansible.posix
    version: 1.3.0
  - name: redhat.rhel_system_roles
    version: 1.16.2
  - name: microsoft.sql
    version: 1.1.0
  - name: azure.azcollection
    version: 1.12.0
