- name: Remove Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: Testing
      name: myVnet
      state: absent
  - name: Add subnet
    azure_rm_subnet:
      resource_group: Testing
      name: mySubnet
      state: absent
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: Testing
      name: myPublicIP
      state: absent
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: Testing
      name: myNetworkSecurityGroup
      state: absent
  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: Testing
      name: myNIC
      virtual_network: myVnet
      subnet: mySubnet
      public_ip_name: myPublicIP
      security_group: myNetworkSecurityGroup
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: Testing
      name: myVM
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      admin_password: Password00!
      ssh_password_enabled: true
      network_interfaces: myNIC
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.3'
        version: latest
