- name: Create Azure Network
  hosts: localhost
  connection: local
  tasks:
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: Testing
      name: myVnet
      address_prefixes: "10.0.0.0/16"
