- name: Create Azure Network
  hosts: localhost
  connection: local
  tasks:
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: "{{ network_name }}"
      address_prefixes: "{{ address_prefixes }}"
