- name: Create Azure Subnet
  hosts: localhost
  connection: local
  tasks:
  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      name: "{{ subnet_name }}"
      address_prefix: "{{ address_prefix }}"
      virtual_network: "{{ network_name }}"

