- name: Create Azure Subnet
  hosts: localhost
  connection: local
  tasks:
  - name: Add subnet
    azure_rm_subnet:
      resource_group: Testing
      name: mySubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: myVnet

