- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create virtual network
    azure.azcollection.azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: myVnet
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure.azcollection.azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      name: mySubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: myVnet
  - name: Create public IP address
    azure.azcollection.azure_rm_publicipaddress:
      resource_group: "{{ resource_group }}"
      allocation_method: Static
      name: myPublicIP
  - name: Create Network Security Group that allows SSH
    azure.azcollection.azure_rm_securitygroup:
      resource_group: "{{ resource_group }}"
      name: myNetworkSecurityGroup
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network inteface card
    azure.azcollection.azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: myNIC
      virtual_network: myVnet
      subnet: mySubnet
      public_ip_name: myPublicIP
      security_group: myNetworkSecurityGroup
  - name: Create VM
    azure.azcollection.azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: myFedora38
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      admin_password: Password00!
      ssh_password_enabled: true
      network_interfaces: myNIC
      managed_disk_type: Standard_LRS
      image:
        offer: fedora-linux-38
        publisher: solvedevops1643693563360
        sku: 'plan001'
        version: latest
      plan:
        name: "plan001"
        publisher: "solvedevops1643693563360"
        product: "fedora-linux-38"
