- name: Update and reboot system
  hosts: all

  tasks:
    - name: Update the system
      ansible.builtin.package:
        name: "*"
        state: latest

    - name: Reboot the machine with all defaults
      ansible.builtin.reboot:
