- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: Testing
      name: myVnet
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: Testing
      name: mySubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: myVnet
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: Testing
      allocation_method: Static
      name: myPublicIP
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: Testing
      name: myNetworkSecurityGroup
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: Testing
      name: myNIC
      virtual_network: myVnet
      subnet: mySubnet
      public_ip_name: myPublicIP
      security_group: myNetworkSecurityGroup
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: Testing
      name: myVM
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      admin_password: 'SecUr3P@s5w0rdSCanBeHard'
      ssh_password_enabled: true
      network_interfaces: myNIC
      tags:
        env: "dev"
        role: "server"
      image:
        offer: "rhel-byos"
        publisher: "redhat"
        sku: "rhel-lvm83"
        version: "latest"
      plan:
        name: "rhel-lvm83"
        publisher: "redhat"
        product: "rhel-byos"
